# Generated by Django 5.2.4 on 2025-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
